"""empty message

Revision ID: 4259b39fbcc3
Revises: 576118018c51
Create Date: 2019-02-03 23:19:31.324133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4259b39fbcc3'
down_revision = '576118018c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fb_targeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_type', sa.String(length=50), nullable=True),
    sa.Column('common_name', sa.String(length=50), nullable=True),
    sa.Column('section_id', sa.String(length=50), nullable=True),
    sa.Column('section_name', sa.String(length=50), nullable=True),
    sa.Column('field_id', sa.String(length=50), nullable=True),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('city_id', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=50), nullable=True),
    sa.Column('country_name', sa.String(length=50), nullable=True),
    sa.Column('audience_size', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fb_targeting')
    # ### end Alembic commands ###
