"""empty message

Revision ID: 576118018c51
Revises: 
Create Date: 2019-02-02 18:02:45.664498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576118018c51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('facebook_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ad_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_account_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_pixel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_pixel_id', sa.String(length=50), nullable=True),
    sa.Column('ad_pixel_name', sa.String(length=50), nullable=True),
    sa.Column('ad_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_account_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('app_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_account_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.String(length=50), nullable=True),
    sa.Column('page_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instagram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_account_id', sa.Integer(), nullable=True),
    sa.Column('instagram_id', sa.String(length=50), nullable=True),
    sa.Column('instagram_user_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instagram')
    op.drop_table('facebook_page')
    op.drop_table('application')
    op.drop_table('ad_pixel')
    op.drop_table('ad_account')
    op.drop_table('user')
    # ### end Alembic commands ###
