"""empty message

Revision ID: b91add601372
Revises: a1e36d11109f
Create Date: 2019-02-10 01:15:40.671330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91add601372'
down_revision = 'a1e36d11109f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_app', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_app', 'user', ['user_id'], ['id'])
    op.add_column('owned_app', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'owned_app', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owned_app', type_='foreignkey')
    op.drop_column('owned_app', 'user_id')
    op.drop_constraint(None, 'client_app', type_='foreignkey')
    op.drop_column('client_app', 'user_id')
    # ### end Alembic commands ###
