"""empty message

Revision ID: de5899fcffae
Revises: b91add601372
Create Date: 2019-02-10 01:28:03.815303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5899fcffae'
down_revision = 'b91add601372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_app_business_id_fkey', 'client_app', type_='foreignkey')
    op.drop_constraint('owned_app_business_id_fkey', 'owned_app', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('owned_app_business_id_fkey', 'owned_app', 'business', ['business_id'], ['id'])
    op.create_foreign_key('client_app_business_id_fkey', 'client_app', 'business', ['business_id'], ['id'])
    # ### end Alembic commands ###
